<?php

namespace app\controllers;
use Yii;
use yii\web\Controller;
use  yii\web\Request;
use yii\helpers\Json;
use yii\rest\ActiveController;
use yii\filters\auth\HttpBasicAuth;
use yii\web\HeaderCollection ;
use yii\web\Application;
use app\models\Users;
use app\models\UserInfo;
use app\models\DeviceLocation;


class ApiController extends ActiveController
{

    public $modelClass = 'app\models\Employee';
    // public $token = 'abc@1234'; //decrypted token
    public $token = '31528198109743225ff9d0cf04d1fdd1'; //md5 token encrypted

    public function beforeAction($action)
    {
        header('Access-Control-Allow-Origin: *');
        header('Content-type: application/json');
        if (isset(getallheaders()['Token']) && $this->token === getallheaders()['Token']) {
            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        } else {
            http_response_code(401);
            echo Json::encode(array(
                "result" => false,
                "error" => "Unauthorized",
            ));
        }
    }

    public function actionTest($id)
    {   //print_r($id);die;
        $user = Users::findOne($id);
//        echo "<pre>";
//        print_r($user);die;
        //$request = CJSON::decode( Yii::$app->request->getRawBody() );
        //print_r($request);die;
        echo JSON::encode($user);

    }

    //Social Login Api As per Required Parameters.

    public function actionSocialLogin()
    {
        $result = [];
        $request = JSON::decode(Yii::$app->request->getRawBody());
        if (($request['method'] == "login") && ($request['loginType'] == "facebook/google/insta/linkedin") && ($request['deviceId'] == "ezjdhhh455hh5jh565") && ($request['deviceType'] == "ios/android")) {
            if (!empty($request['email']) && ($request['socialId'] == "3e44r45r4")) {
                $user = UserInfo::findOne(["email" => $request['email']]);
                if (!empty($user)) {
                    $result = [
                        "code" => 200,
                        "status" => "success",
                        "user Id" => $user['user_id'],
                        "userToken" => $user['user_token'],
                    ];
                } else {
                    $result = [
                        "code" => 500,
                        "message" => "Invalid user/Password",
                    ];
                }
            } else {
                $result = [
                    "code" => 500,
                    "message" => "email and password required",
                ];
            }
        } else {
            $result = [
                "code" => 500,
                "message" => "Invalid user/Password",
            ];
        }
        echo JSON::encode($result);
    }

}
