<?php
namespace app\controllers;
use Yii;
use yii\web\Controller;
use  yii\web\Request;
use yii\helpers\Json;
use yii\rest\ActiveController;
use yii\filters\auth\HttpBasicAuth;
use yii\web\HeaderCollection ;
use yii\web\Application;
use app\models\GroupInfo;
use app\models\UserInfo;
use app\models\FriendsList;
use app\models\GroupMapping;
use app\models\DeviceLocation;
use yii\web\UploadedFile;


class FriendController extends ActiveController
{
    public $modelClass = 'app\models\Employee';
    // public $token = 'abc@1234'; //decrypted token
    public $token = '31528198109743225ff9d0cf04d1fdd1'; //md5 token encrypted

    public function beforeAction($action)
    {
        header('Access-Control-Allow-Origin: *');
        header('Content-type: application/json');
        if (isset(getallheaders()['Token']) && $this->token === getallheaders()['Token']) {
            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        } else {
            http_response_code(401);
            echo Json::encode(array(
                "result" => false,
                "error" => "Unauthorized",
            ));
        }
    }

    //Suggested friend list display

    public function actionSuggestedFriendList()
    {
        $result = [];
        $model = UserInfo::find()->select(['first_name','email','image','about_user'])->All();
        if(!empty($model)) {
            $result = [
                "code" => 200,
                "message" => "success",
                "userData" => [$model],
            ];
        }else{
            $result = [
                "code" => 500,
                "message" => "failed",
            ];
        }
        echo JSON::encode($result);
    }

    //add friend Request

    public function actionAddFriendRequest()
    {
        $result = [];
        $headers = Yii::$app->request->headers;
        $user_id = $headers['user_id'];
        if(!empty($user_id)){
            $request = JSON::decode(Yii::$app->request->getRawBody());
            $request_id = $request['requested_by'];
            if(!empty($request_id)){
                $friend = FriendsList::findOne(["requested_by"=>$request_id,"user_id"=>$user_id]);
                $user = UserInfo::findOne(["user_id"=>$request_id]);
                if(!empty($user)){
                    if(empty($friend)){
                        $model = new FriendsList();
                        $model->requested_by = $request_id;
                        $model->user_id = $user_id;
                        if($model->save()){
                            $result = [
                                "code" => 200,
                                "status" => "success",
                            ];
                        }else{
                            $result = [
                                "code" => 500,
                                "message" => "failed",
                                "error"=> $model->errors,
                            ];
                        }
                    }else{
                        $result = [
                            "code" => 500,
                            "message" => "request alreaady sent",
                        ];
                    }
                }else{
                    $result = [
                        "code" => 500,
                        "message" => "requested user is not found",
                    ];
                }
            }else{
                $result = [
                    "code" => 500,
                    "message" => "request id not found",
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "user id not available",
            ];
        }
        echo JSON::encode($result);
    }

    //accept friend Request

    public function actionAcceptFriendRequest()
    {
        $result = [];
        $headers = Yii::$app->request->headers;
        $user_id = $headers['user_id'];
        if(!empty($user_id)){
            $request = JSON::decode(Yii::$app->request->getRawBody());
            if(isset($request['friend_list_id'])){
                $response_id = $request['friend_list_id'];
                $friend = FriendsList::findOne(["friend_list_id"=>$response_id,"requested_by"=>$user_id]);
                if(!empty($friend)){
                    $friend->status = 1;
                    if($friend->save()){
                        $result = [
                            "code" => 200,
                            "status" => "success",
                        ];
                    }else{
                        $result = [
                            "code" => 500,
                            "message" => "failed",
                            "error"=>$friend->errors,
                        ];
                    }
                }else{
                    $result = [
                        "code" => 500,
                        "message" => "request not found",
                    ];
                }
            }else{
                $result = [
                    "code" => 500,
                    "message" => "response id not available",
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "user id not available",
            ];
        }
        echo JSON::encode($result);
    }
}