<?php
/**
 * Created by PhpStorm.
 * User: Deepak
 * Date: 8/13/2018
 * Time: 2:28 PM
 */


namespace app\controllers;
use Yii;
use yii\web\Controller;
use  yii\web\Request;
use yii\helpers\Json;
use yii\rest\ActiveController;
use yii\filters\auth\HttpBasicAuth;
use yii\web\HeaderCollection ;
use yii\web\Application;
use app\models\Users;
use app\models\UserInfo;
use app\models\DeviceLocation;
use yii\web\UploadedFile;

class HomeController extends ActiveController
{

    public $modelClass = 'app\models\Employee';
    // public $token = 'abc@1234'; //decrypted token
    public $token = '31528198109743225ff9d0cf04d1fdd1'; //md5 token encrypted

    public function beforeAction($action)
    {
        header('Access-Control-Allow-Origin: *');
        header('Content-type: application/json');
        if (isset(getallheaders()['Token']) && $this->token === getallheaders()['Token']) {
            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        } else {
            http_response_code(401);
            echo Json::encode(array(
                "result" => false,
                "error" => "Unauthorized",
            ));
        }
    }

    //Registration Api As per Required Parameters.
    public function actionRegister()
    {
        $result = [];
        $request = JSON::decode(Yii::$app->request->getRawBody());

        $model = new UserInfo();
        $model->attributes = $request;
        $model->password = md5($request['password']);
        $model->date_of_registration = date('Y-m-d H:i:s');
        $model->created_date = date('Y-m-d H:i:s');
        $model->modified_date = date('Y-m-d H:i:s');
//          MD5 hash for admin@123 is : e6e061838856bf47e1de730719fb2609
        $model->user_token = md5(uniqid($model->user_id, true));
        if ($model->save()) {
            $device = new DeviceLocation();
            $device->attributes = $request;
            $device->user_id = $model->user_id;
            $device->created_date = date('Y-m-d H:i:s');
            $device->modified_date = date('Y-m-d H:i:s');
            $device->save();
            $result = [
                "code" => 200,
                "message" => "success",
                "userId" => $model->user_id,
                "userToken" => $model->user_token,
            ];
        } else {
            $result = [
                "code" => 500,
                "message" => "failed",
                "errors" => [$model->errors],
            ];
        }
        echo JSON::encode($result);
    }

    //Login Api As per Required Parameters.
    public function actionLogin()
    {
        $result = [];
        $request = JSON::decode(Yii::$app->request->getRawBody());
        if ((!empty($request['userType'])) && (!empty($request['deviceId'])) && ($request['deviceType'] == "ios" || "android")) {
            if (!empty($request['email']) && !empty($request['password'])) {
                $user = UserInfo::findOne(["email" => $request['email'], "password" => md5($request['password'])]);
                if (!empty($user)) {
                    if($user->gender == 1){
                        $user->gender = "Female";
                    }else{
                        $user->gender = "male";
                    }
                    if($user->is_enabled == 1){
                        $user->is_enabled = "yes";
                    }else{
                        $user->is_enabled = "no";
                    }
                    $userDetails = [
                        "userId"=>$user['user_id'],
                        "userType"=>$user['user_type'],
                        "fullname"=>$user['first_name'].' '.$user['last_name'],
                        "email"=>$user['email'],
                        "gender"=> $user->gender,
                        "dob"=>$user->dob,
                        "aboutme"=>$user->about_user,
                        "goals"=>$user->goals,
                        "focus_area"=>$user->focus_areas,
                        "city"=>$user->city,
                        "country"=>$user->country,
                        "profession"=>$user->profession,
                        "is_verified"=> $user->is_enabled
                    ];

                    $result = [
                        "code" => 200,
                        "status" => "success",
                        "userToken"=>$user->user_token,
                        "userDetails" => $userDetails,
                    ];
                } else {
                    $result = [
                        "code" => 500,
                        "message" => "Invalid user/Password",
                    ];
                }
            } else {
                $result = [
                    "code" => 500,
                    "message" => "email and password required",
                ];
            }
        } else {
            $result = [
                "code" => 500,
                "message" => "Invalid user/Password",
            ];
        }
        echo JSON::encode($result);
    }

    //Social Login Api As per Required Parameters.

    public function actionSocialLogin()
    {
        $result = [];
        $request = JSON::decode(Yii::$app->request->getRawBody());
        if (($request['method'] == "login") && ($request['loginType'] == "facebook" || "google" || "insta" || "linkedin") && ($request['deviceId'] == "ezjdhhh455hh5jh565") && ($request['deviceType'] == "ios" || "android")) {
            if (!empty($request['email']) && (!empty($request['socialId']))) {
                $user = UserInfo::findOne(["email" => $request['email']]);
                if (!empty($user)) {
                    if($user->gender == 1){
                        $user->gender = "Female";
                    }else{
                        $user->gender = "male";
                    }
                    if($user->is_enabled == 1){
                        $user->is_enabled = "yes";
                    }else{
                        $user->is_enabled = "no";
                    }
                    $result = [
                        "code" => 200,
                        "status" => "success",
                        "user Id" => $user['user_id'],
                        "userDetails" => $user,
                    ];
                } else {
                    $result = [
                        "code" => 500,
                        "message" => "Invalid user/Password",
                    ];
                }
            } else {
                $result = [
                    "code" => 500,
                    "message" => "email and password required",
                ];
            }
        } else {
            $result = [
                "code" => 500,
                "message" => "Invalid user/Password",
            ];
        }
        echo JSON::encode($result);
    }

    //get splash Api As per Required Parameters.

    public function actionSplash()
    {
        $result = [];
        $request = JSON::decode(Yii::$app->request->getRawBody());
        $result = [
            "code" => "200",
            "splash" => "http://localhost/asd/img/influ.png",
        ];
        echo JSON::encode($result);
    }

    //register step -2 Api As per Required Parameters.

    public function actionRegisterStep2()

    {
        $result = [];
        $request = JSON::decode(Yii::$app->request->getRawBody());
        if(!empty($request)){
            $id = $request['id'];
            $model = UserInfo::findOne($id);
//        $model->attributes = $request;
            $model->focus_areas = $request['focusArea'];
            $model->about_user = $request['aboutMe'];
            $model->goals = $request['goals'];
            $model->location = $request['location'];
            $model->profession = $request['working'];
            $model->modified_date = date('Y-m-d H:i:s');
            if ($model->save()) {
                $result = [
                    "code" => 200,
                    "message" => "success",
                    "userId" => $model->user_id,
                    "userToken" => $model->user_token,
                ];
            } else {
                $result = [
                    "code" => 500,
                    "message" => [$model->errors],
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => ["No Data Found"],
            ];
        }

        echo JSON::encode($result);
    }

    // update profile using id and update device location

    public function actionEditProfile(){
        $result = [];
        $headers = Yii::$app->request->headers;
        $id = $headers['user_id'];
        if(!empty($id)){
            $user = UserInfo::findOne(["user_id" => $id]);
            if(!empty($user)){
                $request = JSON::decode(Yii::$app->request->getRawBody());
                if(!empty($request)){
                    $user->attributes = $request;
                    $user->modified_date = date('Y-m-d H:i:s');
                    if($user->save()){
                        $device = DeviceLocation::findOne(["user_id" => $id]);
                        if(empty($device)){
                            $device = new DeviceLocation();
                            $device->attributes = $request;
                            $device->user_id = $user->user_id;
                            $device->created_date = date('Y-m-d H:i:s');
                            $device->modified_date = date('Y-m-d H:i:s');
                            if($device->save()) {
                                $result = [
                                    "code" => 200,
                                    "message" => "success",
                                ];
                            }else{
                                $result = [
                                    "code" => 500,
                                    "message" => "failed",
                                    "errors" => [$device->errors],
                                ];
                            }
                        }else{
                            $device->latitude = $request['latitude'];
                            $device->longitude = $request['longitude'];
                            $device->created_date = date('Y-m-d H:i:s');
                            $device->modified_date = date('Y-m-d H:i:s');
                            if($device->save()) {
                                $result = [
                                    "code" => 200,
                                    "message" => "success",
                                ];
                            }else{
                                $result = [
                                    "code" => 500,
                                    "message" => "failed",
                                    "errors" => [$device->errors],
                                ];
                            }
                        }
                    }else{
                        $result = [
                            "code" => 500,
                            "message" => "failed",
                            "errors" =>[$user->errors],
                        ];
                    }
                }else{
                    $result = [
                        "code" => 500,
                        "message" => "data cannot be blank",
                    ];
                }
            }else{
                $result = [
                    "code" => 500,
                    "message" => "user not found",
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "cant get id of user",
            ];
        }
        echo JSON::encode($result);
    }

    // update profile image

    public function actionUpdateProfileImage()
    {
        $result = [];
        $headers = Yii::$app->request->headers;
        $id = $headers['user_id'];
        if(!empty($id)){
            $model = UserInfo::findOne(["user_id" => $id]);
            if(!empty($model)){
                $image = UploadedFile::getInstancesByName('image');
                if(!empty($image)){
                    foreach ($image as $file){
                        $path = Yii::getAlias('@webroot').'/uploads/'.$file->name; //Generate your save file path here;
                        $file->saveAs($path); //Your uploaded file is saved, you can process it further from here
                        $model->image = $file->name;
                        if($model->save()){
                            $result = [
                                "code" => 200,
                                "message" => "success",
                            ];
                        }else{
                            $result = [
                                "code" => 500,
                                "message" => "failed",
                                "errors" => [$model->errors],
                            ];
                        }
                    }
                }else{
                    $result = [
                        "code" => 500,
                        "message" => "image not available",
                    ];
                }
            }else{
                $result = [
                    "code" => 500,
                    "message" => "user not found",
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "cant get id of user",
            ];
        }
        echo JSON::encode($result);
    }

    //deactive account

    public function actionDeactiveAccount()
    {
        $result = [];
        $headers = Yii::$app->request->headers;
        $user_id = $headers['user_id'];
        if(!empty($user_id)){
            $model = UserInfo::findOne(["user_id" => $user_id]);
            if(!empty($model)){
                if($model->is_active == 0 ){
                    $result = [
                        "code" => 500,
                        "message" => "failed",
                        "errors" => "already deactive account",
                    ];
                }else{
                    $model->is_active = 0;
                    if($model->save()){
                        $result = [
                            "code" => 200,
                            "message" => "success",
                        ];
                    }else{
                        $result = [
                            "code" => 500,
                            "message" => "failed",
                            "errors" => [$model->errors],
                        ];
                    }
                }
            }else{
                $result = [
                    "code" => 500,
                    "message" => "user not found",
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "cant get id of user",
            ];
        }
        echo JSON::encode($result);
    }

    //update Location

    public function actionRegisterLocation()
    {
        $result = [];
        $headers = Yii::$app->request->headers;
        $user_id = $headers['user_id'];
        if(!empty($user_id)){
            $request = JSON::decode(Yii::$app->request->getRawBody());
            if(isset($request['latitude']) && isset($request['longitude'])){
                $model = DeviceLocation::findOne(["user_id" => $user_id]);
                if(!empty($model)){
                    $model->attributes = $request;
                    $model->user_id = $user_id;
                    $model->created_date = date('Y-m-d H:i:s');
                    $model->modified_date = date('Y-m-d H:i:s');
                    if ($model->save()) {
                        $result = [
                            "code" => 200,
                            "message" => "success",
                        ];
                    } else {
                        $result = [
                            "code" => 500,
                            "message" => [$model->errors],
                        ];
                    }
                }else{
                    $device = new DeviceLocation();
                    $device->attributes = $request;
                    $device->user_id = $user_id;
                    $device->created_date = date('Y-m-d H:i:s');
                    $device->modified_date = date('Y-m-d H:i:s');
                    if ($device->save()) {
                        $result = [
                            "code" => 200,
                            "message" => "success",
                        ];
                    } else {
                        $result = [
                            "code" => 500,
                            "message" => [$device->errors],
                        ];
                    }
                }
            }else{
                $result = [
                    "code" => 500,
                    "message" => "failed",
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "cant get id of user",
            ];
        }

        echo JSON::encode($result);
    }

    //forget password for the reser password

    public function actionForgetPassword()
    {
        $result = [];
        $request = JSON::decode(Yii::$app->request->getRawBody());
        if (!empty($request['email'])) {
            $user = UserInfo::findOne(["email" => $request['email']]);
            if (!empty($user)) {
                $to = $user['email'];
                $subject = "user password reset";
                $headers = "MIME-Version: 1.0" . "\r\n";
                $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
                $headers .= "From: support@coach.in" . "\r\n" .
                $url = Yii::$app->urlManager->createUrl("users/reset-password");
                    $message = "<html>
                            <body>
                                <table style='border:5px solid #f1f1f1;margin:50px auto;width:500px;'>
                                    <tbody>
                                        <tr width='100%'> 
                                           password reset link <a href='<?php echo ?>'>click here</a>
                                        </tr>
                                    </tbody>
                                </table>
                            </body>
                        </html>";
                if(mail($to, $subject, $message, $headers)){
                    $result = [
                        "code" => 200,
                        "message" => "success",
                    ];
                }else{
                    $result = [
                        "code" => 500,
                        "message" => "failed",
                    ];
                }
            }else{
                $result = [
                    "code" => 500,
                    "message" => "user not found",
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "user id not available",
            ];
        }
    }
}