<?php
namespace app\controllers;
use app\models\Media;
use Yii;
use yii\web\Controller;
use  yii\web\Request;
use yii\helpers\Json;
use yii\rest\ActiveController;
use yii\filters\auth\HttpBasicAuth;
use yii\web\HeaderCollection ;
use yii\web\Application;
use app\models\UserInfo;
use app\models\Posts;
use app\models\Likes;
use app\models\Comments;
use yii\web\UploadedFile;


class PostController extends ActiveController
{
    public $modelClass = 'app\models\Employee';
    // public $token = 'abc@1234'; //decrypted token
    public $token = '31528198109743225ff9d0cf04d1fdd1'; //md5 token encrypted

    public function beforeAction($action)
    {
        header('Access-Control-Allow-Origin: *');
        header('Content-type: application/json');
        if (isset(getallheaders()['Token']) && $this->token === getallheaders()['Token']) {
            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        } else {
            http_response_code(401);
            echo Json::encode(array(
                "result" => false,
                "error" => "Unauthorized",
            ));
        }
    }

    // create Post using image,text,videos

    public function actionCreatePost(){
        $result = [];
        $data = Yii::$app->request->post();
        $headers = Yii::$app->request->headers;
        $user_id = $headers['user_id'];
        if(!empty($user_id)){
            $model = new Posts();
            $model->attributes = $data;
            $model->user_id = $user_id;
            $model->created_date = date('Y-m-d H:i:s');
            $model->modified_date = date('Y-m-d H:i:s');
            if($model->save()){
                if($data['post_type'] != 'text'){
                    $image = UploadedFile::getInstancesByName('url');
                    if(!empty($image)){
                        foreach ($image as $file){
                            $media = new Media();
                            $media->post_id = $model->post_id;
                            $path = Yii::getAlias('@webroot').'/uploads/media/'.$file->name; //Generate your save file path here;
                            $file->saveAs($path); //Your uploaded file is saved, you can process it further from here
                            $media->url = $file->name;
                            $media->created_date = date('Y-m-d H:i:s');
                            $media->modified_date = date('Y-m-d H:i:s');
                            $media->save();
                            if($media->save()){
                                $result = [
                                    "code" => 200,
                                    "message" => "success",
                                ];
                            }else{
                                $result = [
                                    "code" => 500,
                                    "message" => "failed",
                                    "errors" => [$media->errors],
                                ];
                            }
                        }
                    }
                }else{
                    $result = [
                        "code" => 200,
                        "message" => "success",
                    ];
                }
            }else{
                $result = [
                    "code" => 500,
                    "message" => "failed",
                    "errors" => [$model->errors],
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "failed",
            ];
        }
        echo JSON::encode($result);
    }

    //like post

    public function actionLikePost()
    {
        $headers = Yii::$app->request->headers;
        $user_id = $headers['user_id'];
        if(!empty($user_id)){
            $request = JSON::decode(Yii::$app->request->getRawBody());
            $post_id = $request['post_id'];
            $likeuser = Likes::find()->where(['user_id'=>$user_id])->one();
            if(empty($likeuser)){
                $model = new Likes();
                $model->attributes = $request;
                $model->user_id = $user_id;
                $model->created_date = date('Y-m-d H:i:s');
                $model->modified_date = date('Y-m-d H:i:s');
                if($model->save()){
                    $Posts = Posts::find()->where(['post_id'=>$post_id])->one();
                    if(empty($Posts->likes_count)){ $likes = 0; }else{$likes = $Posts->likes_count;}
                    $Posts->likes_count = $likes + 1;
                    if($Posts->save()){
                        $result = [
                            "code" => 200,
                            "message" => "success",
                        ];
                    }else{
                        $result = [
                            "code" => 500,
                            "message" => "failed",
                            "error"=> [$Posts->errors],
                        ];
                    }
                }else{
                    $result = [
                        "code" => 500,
                        "message" => "failed",
                    ];
                }
            }else{
                $result = [
                    "code" => 500,
                    "message" => "already Liked",
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "failed",
            ];
        }
        echo JSON::encode($result);
    }

    //comment post

    public function actionComment()
    {
        $result = [];
        $headers = Yii::$app->request->headers;
        $user_id = $headers['user_id'];
        $request = JSON::decode(Yii::$app->request->getRawBody());
        $post_id = $request['post_id'];
        if(!empty($user_id) && !empty($post_id)) {
            $model = new Comments();
            $model->attributes = $request;
            $model->user_id = $user_id;
            $model->created_date = date('Y-m-d H:i:s');
            $model->modified_date = date('Y-m-d H:i:s');
            if($model->save()){
                $result = [
                    "code" => 200,
                    "message" => "success",
                ];
            }else{
                $result = [
                    "code" => 500,
                    "message" => "failed",
                    "error"=> [$model->errors],
                ];
            }
        }else{
            $result = [
                "code" => 500,
                "message" => "post id and user id not available",
            ];
        }
        echo JSON::encode($result);
    }
}